[Desktop Entry]
UntranslatedGenericName=IPFS Export
Name=IPFS Export
Name[bs]=IPFS Izvoz
Name[ca]=Exportador a IPFS
Name[ca@valencia]=Exportador a IPFS
Name[cs]=Export IPFS
Name[da]=Eksport til IPFS
Name[de]=IPFS-Export
Name[el]=Εξαγωγή IPFS
Name[en_GB]=IPFS Export
Name[es]=Exportar a IPFS
Name[et]=IPFSi eksport
Name[eu]=IPFS-era esportatzea
Name[fi]=IPFS-vienti
Name[fr]=Export « IPFS »
Name[ga]=Easpórtáil IPFS
Name[gl]=Exportación a IPFS
Name[hu]=IPFS exportálás
Name[id]=IPFS Export
Name[is]=IPFS útflutningur
Name[it]=Esportazione a IPFS
Name[km]=នាំចេញ IPFS
Name[ko]=IPFS 내보내기
Name[nb]=IPFS-eksport
Name[nl]=IPFS-export
Name[nn]=IPFS-eksport
Name[pl]=Eksport IPFS
Name[pt]=Exportação para o IPFS
Name[pt_BR]=Exportar para o IPFS
Name[ru]=Экспорт в IPFS
Name[sk]=IPFS Export
Name[sl]=Izvoz IPFS
Name[sv]=Export till IPFS
Name[tr]=IPFS Aktarımı
Name[uk]=Експорт до IPFS
Name[x-test]=xxIPFS Exportxx
Name[zh_CN]=IPFS导出
Name[zh_TW]=IPFS 匯出
Comment=A tool to export images to the ipfs.com image hosting service
Comment[bs]=Alat za izvoz slika u ipfs.com image hosting servisu
Comment[ca]=Una eina per exportar les imatges al servei d'allotjament d'imatges ipfs.com
Comment[ca@valencia]=Una eina per exportar les imatges al servei d'allotjament d'imatges ipfs.com
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby ipfs.com
Comment[da]=Et værktøj til at eksportere billeder til billedupload-tjenesten ipfs.com
Comment[de]=Ein Werkzeug, um Bilder zum ipfs.com-Service zu exportieren.
Comment[el]=Εργαλείο εξαγωγής εικόνων στην υπηρεσία φιλοξενίας εικόνων ipfs.com
Comment[en_GB]=A tool to export images to the ipfs.com image hosting service
Comment[es]=Una herramienta para exportar imágenes al servicio ipfs.com
Comment[et]=Tööriist piltide eksportimiseks ipfs.com-i veebiteenusesse
Comment[eu]=Irudiak urruneko ipfs.com irudi ostatatze zerbitzura esportatzeko tresna bat
Comment[fi]=Kuvien vienti ipfs.com-kuvientallennuspalveluun
Comment[fr]=Outil pour l'export d'images vers le service en ligne d'hébergement d'images « ipfs.com »
Comment[ga]=Uirlis a easpórtálann íomhánna go seirbhís óstála ipfs.com
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web ipfs.com remoto
Comment[hu]=Egy eszköz képek exportálásához az ipfs.com webhelyszolgáltatásba
Comment[id]=Sebuah alat untuk mengekspor gambar ke layanan hosting image ipfs.com
Comment[is]=Verkfæri til að senda myndir á ipfs.com vefþjónustu
Comment[it]=Uno strumento per esportare immagini al servizio di immagini ipfs.com
Comment[km]=ឧបករណ៍​ត្រូវ​នាំចេញ​រូបភាព​ទៅ​ជា​រូបភាព ipfs.com ដោយ​បង្ហោះ​សេវាកម្ម
Comment[ko]=ipfs.com 사진 호스팅 서비스로 사진을 내보내는 도구
Comment[nb]=Et verktøy for å eksportere bilder til bildevertstjenesten ipfs.com
Comment[nl]=Een hulpmiddel om afbeeldingen naar de ipfs.com hostingservice te exporteren
Comment[nn]=Verktøy for eksport av bilete til ipfs.com-tenesta på nettet.
Comment[pl]=Narzędzie do eksportowania obrazów do zdalnej usługi sieciowej ipfs.com
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto do ipfs.com
Comment[pt_BR]=Ferramenta para exportar imagens para o ipfs.com
Comment[ru]=Инструмент для экспорта изображений в веб-службу ipfs.com
Comment[sk]=Nástroj na export obrázkov na hostovaciu službu ipfs.com
Comment[sl]=Orodje za izvoz slik v storitev gostovanja slik ipfs.com
Comment[sv]=Ett verktyg för att exportera bilder till en ipfs.com bildlagringstjänst
Comment[tr]=Resimleri ipfs.com resim barındırma hizmetine aktarmak için bir araç
Comment[uk]=Інструмент для експорту зображень до сховища зображень ipfs.com
Comment[x-test]=xxA tool to export images to the ipfs.com image hosting servicexx
Comment[zh_TW]=匯出影像到 ipfs.com 影像主機服務的工具
Type=Service
Icon=kipi-ipfs
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_ipfs
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_LIB_SO_CUR_VERSION}
author=Marius Orcsik, marius at habarnam dot ro
